version: "3.9"

services:

  attendance:

    image: ghcr.io/msmojtabafar/attendance:latest

    container_name: attendance

    network_mode: host

    environment:
      - DISPLAY=${DISPLAY}

    volumes:

      - /tmp/.X11-unix:/tmp/.X11-unix

      - ./reports:/app/reports

      - ./attendance.db:/app/attendance.db

      - ./fonts:/app/fonts

    restart: unless-stopped